[workspace]
members = ["vault", "wasm"]
resolver = "2"

[profile.release]
# Optimize for size
opt-level = "s"
# Enable link-time optimization
lto = true
# Strip debug symbols
strip = true

[profile.dev]
debug = true

[profile.test]
debug = true
